### ISSUE TITLE
Support changing and deleting items

### ISSUE THREAD

**Issue by sportsracer** [trustyou/comfy#2]
Support assignment to existing options like so:

    config.section.opt = 2

The type of the assigned value should correspond to the option:

* `Option` takes strings, and raises ValueError otherwise
* `IntOption` takes integers …
* Etc.

The changed value should be reflected in the underlying `ConfigParser`, but not in the config files on disk.

Likewise, this should work:

    del config.section.opt

… and delete the value from the `ConfigParser`'s section.

**Comment by Foryah** [comment]
> The type of the assigned value should correspond to the option

If I understand this correctly, we need to validate before the set. Given that our current validation relies on `__get__`, I guess we can do something like this in `__set__`?

```python
old_val = self.__get__(obj)
# Set value code here
...
try:
    self.__get__(obj)
except  (ValueError, TypeError, NoOptionError):
    # Set old_val back and append extra error info here
    ...
    raise
```

**Comment by sportsracer** [comment]
Glad to see you're pondering this ;)

You're right that we should reuse the same type-checking code between getters and setters.

Or maybe it would be an even nicer design to move the type checking into `__set__`, and `__set__` all the values when you construct the comfy object from schema and config parser? Then `__get__`  assumes clean data, and `__set__` makes sure that's the case.

**Comment by Foryah** [comment]
That was my initial idea, but the `ConfigParser` is loading the initial data from the file, the `__init__` from `Section` is only setting the names, whereas the `__set__` should set a name and a value. Or did I understood something wrong?

**Comment by sportsracer** [comment]
Yeah you're right. So maybe we should change the implementation to _not_ read from the underlying `ConfigParser` on every `__get__`, but rather read it once at initialization time, throw errors on invalid types, and then store the sanitized value privately, separate from the `ConfigParser`. Seems cleaner to me!

**Comment by Foryah** [comment]
Yes, I agree. That is way cleaner! I might give it a shot in the next weeks ;)
